--2 SQL Queries
    --2.1 Select statesments
SELECT*FROM CHINOOK.EMPLOYEE;
SELECT * FROM CHINOOK.EMPLOYEE WHERE LASTNAME = 'King';
SELECT*From CHINOOK.EMPLOYEE WHERE FIRSTNAME = 'Andrew' AND REPORTSTO IS NULL;
    --2.2 Order By
SELECT*FROM CHINOOK.ALBUM ORDER BY TITLE ASC;
SELECT FIRSTNAME FROM CHINOOK.CUSTOMER ORDER BY CITY ASC;
    --2.3 INSERT INTO
INSERT INTO CHINOOK.GENRE(GENREID,NAME) VALUES (26,'Current Hip');
INSERT INTO CHINOOK.GENRE(GENREID,NAME) VALUES (27,'Current Hop');

INSERT INTO CHINOOK.EMPLOYEE (EMPLOYEEID,LASTNAME,FIRSTNAME,TITLE,REPORTSTO,BIRTHDATE,HIREDATE,ADDRESS,CITY,STATE,COUNTRY,POSTALCODE,PHONE,FAX,EMAIL)
VALUES (9, 'Adams', 'Andrew', 'General Manager', NULL,TO_DATE('1952-2-18 00:00:00','yyyy-mm-dd hh24:mi:ss'), TO_DATE('2002-8-14 00:00:00','yyyy-mm-dd hh24:mi:ss'), '11120 Jasper Ave NW', 'Edmonton', 'AB', 'Canada', 'T5K 2N1', '+1 (780) 428-9482', '+1 (780) 428-3457', 'andrew@chinookcorp.com');
INSERT INTO CHINOOK.EMPLOYEE (EMPLOYEEID,LASTNAME,FIRSTNAME,TITLE,REPORTSTO,BIRTHDATE,HIREDATE,ADDRESS,CITY,STATE,COUNTRY,POSTALCODE,PHONE,FAX,EMAIL)
VALUES (10, 'Adams2', 'Andrew3', 'General Manager1', 6,TO_DATE('1942-2-18 00:00:00','yyyy-mm-dd hh24:mi:ss'), TO_DATE('2002-8-14 00:00:00','yyyy-mm-dd hh24:mi:ss'), '11120 Jasper Ave NW', 'Edmonton', 'AB', 'Canada', 'T5K 2N1', '+1 (780) 428-9482', '+1 (780) 428-3457', 'andrew@chinookcorp.com');
    --2.4 UPDATE
    